insert into book (id, title, description, author_id, release_year, page_number) values (null, 'The Fat Spy', 'Nam tristique tortor eu pede.', 5, 1952, 99);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Quiet Flows the Don (Tikhiy Don)', 'Pellentesque eget nunc.', 19, 1938, 183);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Rudolph the Red-Nosed Reindeer', 'Phasellus in felis. Donec semper sapien a libero.', 6, 1989, 70);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'King of Kings, The', 'Nulla justo.', 14, 1957, 250);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Irene in Time', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 16, 1977, 158);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'The White Sister', 'Quisque id justo sit amet sapien dignissim vestibulum.', 13, 1962, 45);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Gran Paradiso', 'Integer ac leo. Pellentesque ultrices mattis odio.', 8, 1906, 36);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Conformist, The (Conformista, Il)', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 12, 1983, 151);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Endless Love', 'Sed ante. Vivamus tortor.', 3, 1971, 82);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Bride & Prejudice', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 20, 1921, 76);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Docking the Boat (Att angöra en brygga)', 'Nulla tempus.', 1, 1974, 122);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Snapper, The', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 10, 1996, 293);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Commitments, The', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 19, 2017, 77);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Shadows (Cienie)', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 1, 1946, 132);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Meeting Evil', 'Ut tellus.', 19, 1922, 287);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Hi-Line, The', 'Integer ac leo.', 5, 1934, 244);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Slingshot Hip Hop', 'Donec semper sapien a libero. Nam dui.', 7, 1941, 268);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Killer Holiday', 'Nulla facilisi.', 1, 2003, 147);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Man Called Sledge, A', 'Donec semper sapien a libero.', 9, 1941, 184);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Mean Machine', 'Curabitur convallis.', 18, 2018, 144);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Southern Comfort', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 2, 2017, 155);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Making ''The New World''', 'Vivamus in felis eu sapien cursus vestibulum.', 19, 1909, 131);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Black Tights (1-2-3-4 ou Les Collants noirs)', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 16, 1966, 211);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'White Diamond, The', 'Etiam justo.', 14, 2004, 82);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Slappy and the Stinkers', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 5, 1937, 142);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Moll Flanders', 'Integer a nibh.', 9, 1994, 216);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Beautiful Lies (De vrais mensonges) (Full Treatment)', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 8, 1958, 163);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Food Stamped', 'Nunc rhoncus dui vel sem.', 3, 1969, 284);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Hamlet', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 4, 1901, 96);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Scooby-Doo! and the Witch''s Ghost', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 16, 1914, 61);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Win a Date with Tad Hamilton!', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 14, 1929, 97);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Aurora Borealis', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 6, 1923, 196);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Immortal Sergeant', 'Sed vel enim sit amet nunc viverra dapibus.', 19, 2004, 251);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Nina Frisk', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 10, 1931, 172);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'I Just Didn''t Do It (Soredemo boku wa yattenai)', 'Nam nulla.', 5, 1968, 69);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Broken Blossoms or The Yellow Man and the Girl', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 19, 1959, 39);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Jerusalem Countdown', 'Sed vel enim sit amet nunc viverra dapibus.', 7, 1990, 300);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Brothers Lionheart, The (Bröderna Lejonhjärta)', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 7, 1998, 67);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'White Noise', 'Aenean sit amet justo. Morbi ut odio.', 16, 1963, 81);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Old Dogs', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 12, 2020, 146);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Undercurrent', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 8, 2008, 75);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Talking About Sex', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 4, 1993, 181);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Stormbreaker (Alex Rider: Operation Stormbreaker)', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 6, 1992, 294);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Scenesters, The', 'In congue.', 2, 1989, 299);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Triple Agent', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 18, 1948, 300);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Wuthering Heights', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 7, 1906, 75);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Behold a Pale Horse', 'Nullam porttitor lacus at turpis.', 15, 1993, 176);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Green Ice', 'In hac habitasse platea dictumst.', 15, 1927, 147);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'Bent', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 8, 1913, 159);
insert into book (id, title, description, author_id, release_year, page_number) values (null, 'When We Were Kings', 'Integer tincidunt ante vel ipsum.', 3, 1954, 239);



insert into category (id, name) values (null, 'Comedy');
insert into category (id, name) values (null, 'Musical');
insert into category (id, name) values (null, 'Action');
insert into category (id, name) values (null, 'Drama');
insert into category (id, name) values (null, 'Horror');
insert into category (id, name) values (null, 'War');
insert into category (id, name) values (null, 'Romance');
insert into category (id, name) values (null, 'Mystery');
insert into category (id, name) values (null, 'Children');
insert into category (id, name) values (null, 'Animation');
insert into category (id, name) values (null, 'Adventure');

insert into book_category (id_book, id_category) values (1, 2);
insert into book_category (id_book, id_category) values (2, 5);
insert into book_category (id_book, id_category) values (3, 4);
insert into book_category (id_book, id_category) values (4, 4);
insert into book_category (id_book, id_category) values (5, 4);
insert into book_category (id_book, id_category) values (6, 1);
insert into book_category (id_book, id_category) values (7, 4);
insert into book_category (id_book, id_category) values (8, 5);
insert into book_category (id_book, id_category) values (9, 4);
insert into book_category (id_book, id_category) values (10, 5);
insert into book_category (id_book, id_category) values (11, 5);
insert into book_category (id_book, id_category) values (12, 5);
insert into book_category (id_book, id_category) values (13, 4);
insert into book_category (id_book, id_category) values (14, 1);
insert into book_category (id_book, id_category) values (15, 2);
insert into book_category (id_book, id_category) values (16, 3);
insert into book_category (id_book, id_category) values (17, 3);
insert into book_category (id_book, id_category) values (18, 5);
insert into book_category (id_book, id_category) values (19, 4);
insert into book_category (id_book, id_category) values (20, 3);
insert into book_category (id_book, id_category) values (21, 2);
insert into book_category (id_book, id_category) values (22, 3);
insert into book_category (id_book, id_category) values (23, 5);
insert into book_category (id_book, id_category) values (24, 3);
insert into book_category (id_book, id_category) values (25, 1);
insert into book_category (id_book, id_category) values (26, 1);
insert into book_category (id_book, id_category) values (27, 1);
insert into book_category (id_book, id_category) values (28, 3);
insert into book_category (id_book, id_category) values (29, 5);
insert into book_category (id_book, id_category) values (30, 3);
insert into book_category (id_book, id_category) values (31, 2);
insert into book_category (id_book, id_category) values (32, 3);
insert into book_category (id_book, id_category) values (33, 1);
insert into book_category (id_book, id_category) values (34, 2);
insert into book_category (id_book, id_category) values (35, 2);
insert into book_category (id_book, id_category) values (36, 2);
insert into book_category (id_book, id_category) values (37, 1);
insert into book_category (id_book, id_category) values (38, 5);
insert into book_category (id_book, id_category) values (39, 5);
insert into book_category (id_book, id_category) values (40, 5);
insert into book_category (id_book, id_category) values (41, 3);
insert into book_category (id_book, id_category) values (42, 1);
insert into book_category (id_book, id_category) values (43, 2);
insert into book_category (id_book, id_category) values (44, 5);
insert into book_category (id_book, id_category) values (45, 5);
insert into book_category (id_book, id_category) values (46, 2);
insert into book_category (id_book, id_category) values (47, 1);
insert into book_category (id_book, id_category) values (48, 2);
insert into book_category (id_book, id_category) values (49, 3);
insert into book_category (id_book, id_category) values (50, 3);
insert into book_category (id_book, id_category) values (51, 5);
insert into book_category (id_book, id_category) values (52, 4);